server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://139.196.194.49/upload_model?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: root
    username: root
  redis:
    host: localhost
    password: root
    port: 8761
    timeout: 6000
debug: true
logging:
  level:
    org.springframework.security.*: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
#  jwt私钥密匙
  secret: "JWTSuperSecretKey"
#  过期时间 7天
  expirationInMs: 604800000
  authorization: "Authorization"
  bearer: "Bearer"
redis:
  accessKey: "access"
  hashKeyPrefix: "jwtUser_"