server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://139.196.194.49:3306/upload_model
    password: root
    username: root
  redis:
    host: 47.103.147.93
    password: root
    port: 6379
    timeout: 6000
debug: true
logging:
  level:
    org.springframework.security.*: debug
    com.baomidou.example.mapper: debug
jwt:
#  jwt私钥密匙
  secret: "JWTSuperSecretKey"
#  过期时间 7天
  expirationInMs: 604800000
  authorization: "Authorization"
  bearer: "Bearer"
redis:
  accessKey: "access"
  hashKeyPrefix: "jwtUser_"