server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://139.196.194.49:3306/upload_model
    password: root
    username: root
  redis:
    host: 47.103.147.93
    password: root
    port: 6379
debug: true
logging:
  level:
    org.springframework.security: debug
# redis